In [0]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [0]:
tf.__version__

'2.2.0-rc3'

In [0]:
from google.colab import files

In [0]:
uploaded=files.upload()

Saving Churn_Modelling.csv to Churn_Modelling.csv


In [0]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [0]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [0]:
from sklearn.preprocessing import LabelEncoder
ec=LabelEncoder()
X[:,2]=ec.fit_transform(X[:,2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [0]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [0]:
# #to see the indexes of X
# see=pd.DataFrame(X)
# print(see.head())

   0  1  2    3  4   5  6        7  8  9 10       11
0  1  0  0  619  0  42  2        0  1  1  1   101349
1  0  0  1  608  0  41  1  83807.9  1  0  1   112543
2  1  0  0  502  0  42  8   159661  3  1  0   113932
3  1  0  0  699  0  39  1        0  2  0  0  93826.6
4  0  0  1  850  0  43  2   125511  1  1  1  79084.1


In [0]:
X=X[:,1:]

In [0]:
#to see the indexes of X
see=pd.DataFrame(X)
print(see.head())

   0  1    2  3   4  5        6  7  8  9       10
0  0  0  619  0  42  2        0  1  1  1   101349
1  0  1  608  0  41  1  83807.9  1  0  1   112543
2  0  0  502  0  42  8   159661  3  1  0   113932
3  0  0  699  0  39  1        0  2  0  0  93826.6
4  0  1  850  0  43  2   125511  1  1  1  79084.1


In [0]:
#feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X[:,[2,4,5,6,7,10]]=sc.fit_transform(X[:,[2,4,5,6,7,10]])

In [0]:
#to see the indexes of X
see=pd.DataFrame(X)
print(see.head())

   0  1         2  3           4        5         6         7  8  9         10
0  0  0 -0.326221  0    0.293517 -1.04176  -1.22585 -0.911583  1  1  0.0218865
1  0  1 -0.440036  0    0.198164 -1.38754   0.11735 -0.911583  0  1   0.216534
2  0  0  -1.53679  0    0.293517  1.03291   1.33305   2.52706  1  0   0.240687
3  0  0  0.501521  0  0.00745665 -1.38754  -1.22585  0.807737  0  0  -0.108918
4  0  1   2.06388  0    0.388871 -1.04176  0.785728 -0.911583  1  1  -0.365276


In [0]:
#splitting
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [0]:
#Building Model
ann=tf.keras.models.Sequential()

In [0]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [0]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [0]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [0]:
#compiling the ANN
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [0]:
x_train=np.asarray(x_train).astype(np.float32)
x_test=np.asarray(x_test).astype(np.float32)


In [0]:
# #TensorBoard
# log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
# tensorboard_callback=tf.keras.callbacks.TensorBoard(log_dir=log_dir,histogram_freq=1)

In [0]:
#fitting the model
ann.fit(x_train,y_train,batch_size=30,epochs=100)

Epoch 1/100
267/267 [==============================] - 0s 1ms/step - loss: 0.3312 - accuracy: 0.8624
Epoch 2/100
267/267 [==============================] - 0s 1ms/step - loss: 0.3307 - accuracy: 0.8641
Epoch 3/100
267/267 [==============================] - 0s 1ms/step - loss: 0.3304 - accuracy: 0.8645
Epoch 4/100
267/267 [==============================] - 0s 1ms/step - loss: 0.3308 - accuracy: 0.8643
Epoch 5/100
267/267 [==============================] - 0s 1ms/step - loss: 0.3308 - accuracy: 0.8651
Epoch 6/100
267/267 [==============================] - 0s 1ms/step - loss: 0.3306 - accuracy: 0.8646
Epoch 7/100
267/267 [==============================] - 0s 1ms/step - loss: 0.3303 - accuracy: 0.8664
Epoch 8/100
267/267 [==============================] - 0s 1ms/step - loss: 0.3304 - accuracy: 0.8633
Epoch 9/100
267/267 [==============================] - 0s 1ms/step - loss: 0.3305 - accuracy: 0.8627
Epoch 10/100
267/267 [==============================] - 0s 1ms/step - loss: 0.3307 - accura

In [0]:
# #Launching TensorBoard
# %tensorboard --logdir logs/fit

In [0]:
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [0]:
#making confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[1518   77]
 [ 201  204]]


In [0]:
print(y_pred.reshape(1,len(y_pred)))

[[False False False ... False False False]]
